sudo: required
services:
 - docker

before_install:
 - docker build -t nlaparo/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true nlaparo/docker-react npm run test

deploy:
 provider: elastic beanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-1-368962257872"
 bucket_path: "docker-react"
 on:
  branch: master

access_key_id:
 secure: "$AWS_ACCESS_KEY"
secret_access_key:
 secure: "$AWS_SECRET_KEY"
